#ifndef THRUST_CALCULATOR_H
#define THRUST_CALCULATOR_H

#include "RPATableInterpolator.h"
#include <memory>

/**
 * ThrustCalculator
 *
 * Calculates rocket engine thrust at each timestep using the chamber pressure equation:
 *
 *     F = Cf × Pc × At
 *
 * Where:
 *   - F  = Thrust (lbf or N)
 *   - Cf = Thrust coefficient (from RPA tables, varies with Pc, O/F, Pa)
 *   - Pc = Chamber pressure (from injector/feed system model)
 *   - At = Throat area (fixed from engine sizing)
 *
 * Usage:
 *   1. Size the engine (set throat area) based on design requirements
 *   2. Load RPA performance tables
 *   3. Each timestep: provide Pc, mdot_ox, mdot_fuel, Pa -> get thrust
 */
class ThrustCalculator {
public:
    ThrustCalculator();
    ~ThrustCalculator();

    /**
     * Load RPA performance table
     * @param table_filename Path to CSV file generated by generate_rpa_tables.js
     * @return true if successful
     */
    bool loadPerformanceTable(const std::string& table_filename);

    /**
     * Set engine throat area (from engine sizing)
     * @param At_in2 Throat area in square inches
     */
    void setThroatArea(double At_in2);

    /**
     * Set engine throat area using design point
     * Calculates At from design thrust and chamber pressure
     * @param F_design Design thrust (lbf)
     * @param Pc_design Design chamber pressure (psi)
     * @param OF_design Design mixture ratio
     * @param Pa_design Design ambient pressure (psi)
     */
    void sizeEngineFromDesignPoint(double F_design, double Pc_design,
                                   double OF_design, double Pa_design);

    /**
     * Calculate thrust at current operating conditions
     * Uses chamber pressure equation: F = Cf × Pc × At
     *
     * @param Pc Chamber pressure (psi)
     * @param mdot_ox Oxidizer mass flow rate (lbm/s)
     * @param mdot_fuel Fuel mass flow rate (lbm/s)
     * @param Pa Ambient pressure (psi)
     * @return Thrust (lbf)
     */
    double calculateThrust(double Pc, double mdot_ox, double mdot_fuel, double Pa);

    /**
     * Get the current performance data from last calculation
     */
    RPATableInterpolator::PerformanceData getLastPerformanceData() const {
        return m_lastPerformance;
    }

    /**
     * Get throat area (in^2)
     */
    double getThroatArea() const { return m_At_in2; }

    /**
     * Alternative thrust calculation using mass flow and C*
     * F = mdot × C* × Cf
     * Useful for verification or when you trust mdot more than Pc
     */
    double calculateThrustFromMassFlow(double mdot_total, double OF, double Pa);

    /**
     * Check if calculator is ready to use
     */
    bool isReady() const {
        return m_tableInterpolator && m_tableInterpolator->isValid() && m_At_in2 > 0.0;
    }

private:
    std::unique_ptr<RPATableInterpolator> m_tableInterpolator;
    double m_At_in2;  // Throat area (square inches)
    RPATableInterpolator::PerformanceData m_lastPerformance;
};

#endif // THRUST_CALCULATOR_H
